name: image-syncer

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Log into aliyun registry
      - name: Log into aliyun registry
        run: echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login $ALIYUN_REGISTRY -u ${{ secrets.ALIYUN_USERNAME }} --password-stdin

      - name: Download image-syncer
        run: |
          wget https://github.com/AliyunContainerService/image-syncer/releases/download/v1.3.1/image-syncer-v1.3.1-linux-amd64.tar.gz
          tar xvfz image-syncer-v1.3.1-linux-amd64.tar.gz

      - name: Sync images
        run: |
          ./image-syncer --auth=auth.yaml --images=images.yaml
        env:
          ALIYUN_REGISTRY_USERNAME: ${{ secrets.ALIYUN_USERNAME }}
          ALIYUN_REGISTRY_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
